define([
	'./modules/Focus',
	'./modules/VScroller',
	'./modules/ColumnResizer',
	'./modules/VirtualVScroller',
	'./modules/SingleSort',
	'./modules/NestedSort',
	'./modules/Sort',
	'./modules/ColumnLock',
	'./modules/select/Row',
	'./modules/select/Column',
	'./modules/select/Cell',
	'./modules/extendedSelect/Row',
	'./modules/extendedSelect/Column',
	'./modules/extendedSelect/Cell',
	'./modules/move/Row',
	'./modules/move/Column',
	'./modules/dnd/Row',
	'./modules/dnd/Column',
	'./modules/Pagination',
	'./modules/pagination/PaginationBar',
	'./modules/pagination/PaginationBarDD',
	'./modules/Filter',
	'./modules/filter/FilterBar',
	'./modules/filter/QuickFilter',
	'./modules/CellWidget',
	'./modules/Edit',
	'./modules/RowHeader',
	'./modules/IndirectSelect',
	'./modules/IndirectSelectColumn',
	'./modules/Persist',
	'./modules/Menu',
	'./modules/Dod',
	'./modules/Tree',
	'./modules/RowLock',
	'./modules/ToolBar',
	'./modules/SummaryBar',
	'./modules/Bar',
	'./modules/NavigableCell',
	'./modules/TouchScroll',
	'./modules/TouchVScroller',
	'./modules/HiddenColumns',
	'./modules/GroupHeader',
	'./modules/PagedBody',
	'./modules/AutoPagedBody',
	'./modules/HeaderMenu',
	'./modules/HeaderRegions',
	'./modules/SlantedHeader',
	'./modules/ExpandableColumn',
	'./modules/Layer',
	'./modules/StructureSwitch'
], function(
	Focus, VScroller, ColumnResizer, VirtualVScroller,
	SingleSort, NestedSort, Sort, ColumnLock,
	SelectRow, SelectColumn, SelectCell,
	ExtendedSelectRow, ExtendedSelectColumn, ExtendedSelectCell,
	MoveRow, MoveColumn,
	DndRow, DndColumn,
	Pagination,
	PaginationBar, PaginationBarDD,
	Filter, FilterBar, QuickFilter,
	CellWidget, Edit,
	RowHeader, IndirectSelect, IndirectSelectColumn,
	Persist, Menu, Dod, Tree, RowLock,
	ToolBar, SummaryBar, Bar, NavigableCell, TouchScroll, TouchVScroller,
	HiddenColumns, GroupHeader, PagedBody, AutoPagedBody,
	HeaderMenu, HeaderRegions, SlantedHeader, ExpandableColumn,
	Layer, StructureSwitch){
return {
	Focus: Focus,
	VScroller: VScroller,
	ColumnResizer: ColumnResizer,
	VirtualVScroller: VirtualVScroller,
	SingleSort: SingleSort,
	NestedSort: NestedSort,
	Sort: Sort,
	ColumnLock: ColumnLock,
	SelectRow: SelectRow,
	SelectColumn: SelectColumn,
	SelectCell: SelectCell,
	ExtendedSelectRow: ExtendedSelectRow,
	ExtendedSelectColumn: ExtendedSelectColumn,
	ExtendedSelectCell: ExtendedSelectCell,
	MoveRow: MoveRow,
	MoveColumn: MoveColumn,
	DndRow: DndRow,
	DndColumn: DndColumn,
	Pagination: Pagination,
	PaginationBar: PaginationBar,
	PaginationBarDD: PaginationBarDD,
	Filter: Filter,
	FilterBar: FilterBar,
	QuickFilter: QuickFilter,
	CellWidget: CellWidget,
	Edit: Edit,
	RowHeader: RowHeader,
	IndirectSelect: IndirectSelect,
	IndirectSelectColumn: IndirectSelectColumn,
	Persist: Persist,
	Menu: Menu,
	Dod: Dod,
	Tree: Tree,
	RowLock: RowLock,
	ToolBar: ToolBar,
	SummaryBar: SummaryBar,
	Bar: Bar,
	NavigableCell: NavigableCell,
	TouchScroll: TouchScroll,
	TouchVScroller: TouchVScroller,
	HiddenColumns: HiddenColumns,
	GroupHeader: GroupHeader,
	PagedBody: PagedBody,
	AutoPagedBody: AutoPagedBody,
	HeaderMenu: HeaderMenu,
	HeaderRegions: HeaderRegions,
	SlantedHeader: SlantedHeader,
	ExpandableColumn: ExpandableColumn,
	Layer: Layer,
	StructureSwitch: StructureSwitch
};
});
