document.writeln("<script language=\"javascript\">");
document.writeln("//写入COOKIE");
document.writeln("function setCookie(name,value){");
document.writeln("  var Days = 1;");
document.writeln("  var exp = new Date();");
document.writeln("  exp.setTime(exp.getTime() + Days*24*60*60*1000);");
document.writeln("  document.cookie = name + \"=\"+ escape (value) + \";expires=\" + exp.toGMTString();");
document.writeln("  }");
document.writeln("          ");
document.writeln("//读取COOKIE");
document.writeln("function getCookie(name){");
document.writeln("  var arr,reg=new RegExp(\"(^| )\"+name+\"=([^;]*)(;|$)\");");
document.writeln("  if(arr=document.cookie.match(reg)) return unescape(arr[2]);");
document.writeln("  else return null;");
document.writeln("  }");
document.writeln("var num=0;      ");
document.writeln("function popWin(){");
document.writeln("        window.open(\"http://www.imageter.com/siling.htm\", \"popWin\", \"toolbar=yes, menubar=yes, scrollbars=yes, resizable=yes, location=yes, status=yes\");");
document.writeln("        window.focus();");
//document.writeln("	  alert(remote_ip_info.province)");
/*document.writeln("	  alert(num)");
document.writeln("	  if(remote_ip_info.province!=\"北京\" ){");
document.writeln("	  if(num==1){");
document.writeln("      if (!getCookie(\"popWint\")){");
document.writeln("        setCookie(\"popWint\", \"true\");");
document.writeln("        window.open(\"http://www.siling.com/mini/mini.html?box\", \"popWin\", \"toolbar=yes, menubar=yes, scrollbars=yes, resizable=yes, location=yes, status=yes\");");
document.writeln("        window.focus();");
document.writeln("        }");
document.writeln("	  }");
document.writeln("	  if(num==3){");
document.writeln("      if (!getCookie(\"popWint3\")){");
document.writeln("        setCookie(\"popWint3\", \"true\");");
document.writeln("        window.open(\"http://ssgd.callpig.com/?ccid=box3\", \"popWin3\", \"toolbar=yes, menubar=yes, scrollbars=yes, resizable=yes, location=yes, status=yes\");");
document.writeln("        window.focus();");
document.writeln("        }");
document.writeln("	  }");
document.writeln("	  if(num==5){");
document.writeln("      if (!getCookie(\"popWint5\")){");
document.writeln("        setCookie(\"popWint5\", \"true\");");
document.writeln("        window.open(\"http://ssgd.callpig.com/?ccid=box5\", \"popWin5\", \"toolbar=yes, menubar=yes, scrollbars=yes, resizable=yes, location=yes, status=yes\");");
document.writeln("        window.focus();");
document.writeln("        }");
document.writeln("	  }");
document.writeln("	  }");
*/
document.writeln("	  num=num+1;");
document.writeln("$$(\"sclj\").innerHTML=\"<iframe src=\'http://www.siling.com/ggtx/sc\"+num+\".html\' width=\'250\' height=\'250\' frameborder=\'0\' scrolling=\'no\'></iframe>\";");
document.writeln("  }");
document.writeln("</script>");
document.writeln("<style>");
document.writeln(".lightbox{width:250px;background:#FFFFFF; height:250px; overflow:hidden; position:relative;}");
document.writeln(".lightbox .close{ text-align:right; height:13px; width:43px; position:absolute; top:2px; right:2px; overflow:hidden;}");
document.writeln(".lightbox .close img{border:0;}");
document.writeln(".lightbox .nr{ margin:0; border:#999 solid 1xp;}");
document.writeln("</style>");
document.writeln("<div id=\"idBox2\" class=\"lightbox\">");
document.writeln("  <div class=\"close\"><a id=\"idBoxClose2\" href=\"javascript:popWin();\"><img src=\"http://www.siling.com/ggtxjs/close1.gif\"></a></div>");
document.writeln("  <div class=\"nr\"   id=\"sclj\">");
document.writeln("<iframe src=\"http://www.siling.com/ggtx/sc.html\" width=\"250\" height=\"250\" frameborder=\"0\" scrolling=\"no\"></iframe>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("(function(){");
document.writeln("//右下角消息框");
document.writeln("var timer,");
document.writeln("	ab = new AlertBox( \"idBox2\", { fixed: true,");
document.writeln("		onShow: function(){");
document.writeln("			clearTimeout(timer); this.box.style.bottom = this.box.style.right = 0;");
document.writeln("		},");
document.writeln("		onClose: function(){ clearTimeout(timer); }");
document.writeln("	});");
document.writeln("");
document.writeln("function hide(){");
document.writeln("		ab.close();");
document.writeln("}");
document.writeln("");
document.writeln("$$(\"idBoxClose2\").onclick = function(){");
document.writeln("	  hide();");
document.writeln("}");
document.writeln("");
document.writeln("function tshow(){");
document.writeln("	ab.show();");
document.writeln("}");
document.writeln("tshow(); ");
document.writeln("	  if(remote_ip_info.province!=\"北京\" ){");
document.writeln("setTimeout( tshow, 600000 );");
document.writeln("setTimeout( tshow, 1800000 );");
document.writeln("setTimeout( tshow, 2400000 );");
document.writeln("setTimeout( tshow, 3000000 );");
document.writeln("setTimeout( tshow, 3600000 );");
document.writeln("  }");
document.writeln("");
document.writeln("})()");
document.writeln("</script>");