define({     
//Body
	loadingInfo: "Učitavanje...",
	emptyInfo: "Nema stavki za prikaz",
	loadFailInfo: "Neuspješno učitavanje podataka",
	loadMore: "Učitaj još",
	loadMoreLoading: "Učitavanje...",
	loadPrevious: "Učitaj prethodno",
	loadPreviousLoading: "Učitavanje...",

//FilterBar
	"clearFilterDialogTitle": "Brisanje filtera",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Nijedan filter nije primijenjen",
	"defineFilter": "Definisanje filtera",
	"conditionEqual": "jednako",
	"conditionNotEqual": "nije jednako",
	"conditionLess": "manje je od",
	"conditionLessEqual": "manje od ili jednako",
	"conditionGreater": "veće je od",
	"conditionGreaterEqual": "veće od ili jednako",
	"conditionContain": "sadrži",
	"conditionIs": "je",
	"conditionStartWith": "počinje sa",
	"conditionEndWith": "završava sa",
	"conditionNotContain": "ne sadrži",
	"conditionIsNot": "nije",
	"conditionNotStartWith": "ne počinje sa",
	"conditionNotEndWith": "ne završava sa",
	"conditionBefore": "prije",
	"conditionAfter": "nakon",
	"conditionRange": "interval",
	"conditionIsEmpty": "je prazno",
	"all": "svi",
	"any": "bilo koji",
	"relationAll": "sva pravila",
	"waiRelAll": "Spari sve sljedeća pravila:",
	"relationAny": "bilo koje pravilo",
	"waiRelAny": "Spari bilo koje od sljedećih pravila:",
	"relationMsgFront": "Spari",
	"relationMsgTail": "",
	"and": "i",
	"or": "ili",
	"addRuleButton": "Dodaj pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Ukloni pravilo",
	"waiRemoveRuleButtonTemplate": "Ukloni pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtera",
	"cancelButton": "Odustani",
	"waiCancelButton": "Odustani od ovog prijedloga",
	"clearButton": "Briši",
	"waiClearButton": "Briši filter",
	"filterButton": "Filter",
	"waiFilterButton": "Submitiraj filter",
	"columnSelectLabel": "Kolona:",
	"waiColumnSelectTemplate": "Kolona za pravilo ${0}",
	"conditionSelectLabel": "Uslov:",
	"waiConditionSelectTemplate": "Uslov za pravilo ${0}",
	"valueBoxLabel": "Vrijednost:",
	"waiValueBoxTemplate": "Unos vrijednosti u filter za  pravilo ${0}",
	"rangeTo": "u",
	"rangeTemplate": "iz ${0} u ${1}",
	"statusTipHeaderColumn": "Kolona",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Traka filtera",
	"statusTipMsg": "Kliknite ovdje traku za filtriranje po vrijednostima u ${0}.",
	"anycolumn": "bilo koja kolona",
	"statusTipTitleNoFilter": "Traka filtera",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Spari",
	"statusTipRelPost": "pravila.",
	"statusTipHeaderAll": "Spari sva pravila",
	"statusTipHeaderAny": "Spari bilo koja pravila.",
	"defaultItemsName": "stavke",
	"filterBarMsgHasFilterTemplate": "${0} od ${1} ${2} je prikazano.",
	"filterBarMsgNoFilterTemplate": "Nijedan filter nije primijenjen",
	"filterBarDefButton": "Definiši filter",
	"waiFilterBarDefButton": "Filtriraj tabelu",
	"a11yFilterBarDefButton": "Filtriranje...",
	"filterBarClearButton": "Briši filter",
	"waiFilterBarClearButton": "Briši filter",
	"closeFilterBarBtn": "Zatvori traku filtera",
	"clearFilterMsg": "To će ukloniti filter i pokazati sve raspoložive slogove.",
	"anyColumnOption": "Bilo koju kolonu",
	"trueLabel": "Tačno",
	"falseLabel": "Netačno",
	"radioTrueLabel": "Vrijednost tačno",
	"radioFalseLabel": "Vrijednost netačno",
	"beginTimeRangeLabel": "Početak vrijednosti intervala vremena",
	"endTimeRangeLabel": "Kraj vrijednosti intervala vremena",
	"beginDateRangeLabel": "Početak vrijednosti intervala datuma",
	"endDateRangeLabel": "Kraj vrijednosti intervala datuma",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Pojedinačan sort",
	nestedSort: "Ugniježđeni sort",
	ascending: "Kliknite za uzlazno sortiranje",
	descending: "Kliknite za silazno sortiranje",
	sortingState: "${0} - ${1}",
	unsorted: "Ne sortiraj ova kolonu",
	waiSingleSortLabel: "${0} - je sortirao ${1}. Izaberite sort po ${2}",
	waiNestedSortLabel:"${0} - ne ugniježđeni sort po ${1}. Izaberite ugniježđeni sort po ${2}",

//PaginationBar
	pagerWai: 'Dojavljivač',

	pageIndex: '${0}',
	pageIndexTitle: 'Stranica ${0}',

	firstPageTitle: 'Prva stranica',
	prevPageTitle: 'Prethodna stranica',
	nextPageTitle: 'Sljedeća stranica',
	lastPageTitle: 'Zadnja stranica',

	pageSize: '${0}',
	pageSizeTitle: '${0} stavaka po stranici',
	pageSizeAll: 'Sve',
	pageSizeAllTitle: 'Sve stavke',

	description: '${0} - ${1} od ${2} stavaka.',
	descriptionEmpty: 'Rešetka je prazna.',

	summary: 'Ukupno: ${0}',
	summaryWithSelection: 'Ukupno: ${0} Izabrano: ${1}',

	gotoBtnTitle: 'Idi na određenu stranicu',

	gotoDialogTitle: 'Idi na stranicu',
	gotoDialogMainMsg: 'Navedite broj stranice:',
	gotoDialogPageCount: '(${0} stranica)',
	gotoDialogOKBtn: 'Idi',
	gotoDialogCancelBtn: 'Odustani',
	// for drop down pagination bar
	pageLabel: 'Stranice',
	pageSizeLabel: 'Redovi',

//QuickFilter
	filterLabel: 'Filter',
	clearButtonTitle: 'Briši filter',
	buildFilterMenuLabel: 'Izgradnja filter&hellip;',
	apply: 'Primijeni filter',

//Sort
	helpMsg: '${0} - Kliknite za sortiranje ili kliknite kontrola za dodavanje sorta',
	singleHelpMsg: '${0} - Kliknite za sortiranje',
	priorityOrder: 'prioritet sorta ${0}',

//SummaryBar
	summaryTotal: 'Ukupno: ${0}',
	summarySelected: 'Izabrano: ${0}',
	summaryRange: 'Raspon: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Pritisnite SPACE da biste sve izabrali.",	//need translation
	indirectDeselectAll: "Pritisnite SPACE da biste odznačili sve.",	//need translation
	treeExpanded: "Kontrola + tipka sa strelicom lijevo za skupljanje ovog reda.",	//need translation
	treeCollapsed: "Kontrola + tipka sa strelicom desno za proširivanje ovog reda."	//need translation
});

