define({     
//Body
	loadingInfo: "Вчитување...",
	emptyInfo: "Нема ставки за приказ",
	loadFailInfo: "Не успеа да вчита податоци!",
	loadMore: "Вчитај повеќе",
	loadMoreLoading: "Вчитување...",
	loadPrevious: "Вчитај претходно",
	loadPreviousLoading: "Вчитување...",

//FilterBar
	"clearFilterDialogTitle": "Исчисти филтер",
	"filterDefDialogTitle": "Филтер",
	"defaultRuleTitle": "Правило",
	"ruleTitleTemplate": "Правило ${ruleNumber}",
	"noFilterApplied": "Нема применето филтер.",
	"defineFilter": "Дефинирај филтер",
	"conditionEqual": "еднакво",
	"conditionNotEqual": "не е еднакво",
	"conditionLess": "е помало од",
	"conditionLessEqual": "помало од или еднакво",
	"conditionGreater": "е поголемо од",
	"conditionGreaterEqual": "поголемо од или еднакво на",
	"conditionContain": "содржи",
	"conditionIs": "е",
	"conditionStartWith": "почнува со",
	"conditionEndWith": "завршува со",
	"conditionNotContain": "не содржи",
	"conditionIsNot": "не е",
	"conditionNotStartWith": "не почнува со",
	"conditionNotEndWith": "не завршува со",
	"conditionBefore": "пред",
	"conditionAfter": "после",
	"conditionRange": "опсег",
	"conditionIsEmpty": "е празно",
	"all": "сите",
	"any": "кои било",
	"relationAll": "сите правила",
	"waiRelAll": "Се совпаѓа со сите следни правила:",
	"relationAny": "кое било правило",
	"waiRelAny": "Се совпаѓа со кое било од следниве правила:",
	"relationMsgFront": "Се совпаѓа",
	"relationMsgTail": "",
	"and": "и",
	"or": "или",
	"addRuleButton": "Додај правило",
	"waiAddRuleButton": "Додај ново правило",
	"removeRuleButton": "Отстрани правило",
	"waiRemoveRuleButtonTemplate": "тстрани го правилото ${0}",
	"addRuleButton": "Додај правило за филтер",
	"cancelButton": "Откажи",
	"waiCancelButton": "Откажи го овој дијалог",
	"clearButton": "Исчисти",
	"waiClearButton": "Исчисти го филтерот",
	"filterButton": "Филтрирај",
	"waiFilterButton": "Поднеси го филтерот",
	"columnSelectLabel": "Колона:",
	"waiColumnSelectTemplate": "Колона за правилото ${0}",
	"conditionSelectLabel": "Услов:",
	"waiConditionSelectTemplate": "Услов за правилото ${0}",
	"valueBoxLabel": "Вредност:",
	"waiValueBoxTemplate": "Внесете вредност за филтер на правилото ${0}",
	"rangeTo": "до",
	"rangeTemplate": "од ${0} до ${1}",
	"statusTipHeaderColumn": "Колона",
	"statusTipHeaderCondition": "Правила",
	"statusTipTitle": "Лента за филтер",
	"statusTipMsg": "Кликнете на лентата за филтер тука за да филтрирате вредности во ${0}.",
	"anycolumn": "која било колона",
	"statusTipTitleNoFilter": "Лента за филтер",
	"statusTipTitleHasFilter": "Филтрирај",
	"statusTipRelPre": "Се совпаѓа",
	"statusTipRelPost": "правила.",
	"statusTipHeaderAll": "Совпаѓање на сите правила.",
	"statusTipHeaderAny": "Совпаѓање на кои било правила.",
	"defaultItemsName": "ставки",
	"filterBarMsgHasFilterTemplate": "Се прикажува ${0} од ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Нема применето филтер",
	"filterBarDefButton": "Дефинирај филтер",
	"waiFilterBarDefButton": "Филтрирај табела",
	"a11yFilterBarDefButton": "Филтер...",
	"filterBarClearButton": "Исчисти филтер",
	"waiFilterBarClearButton": "Исчисти го филтерот",
	"closeFilterBarBtn": "Затвори лента за филтер",
	"clearFilterMsg": "Со ова филтерот се отстранува и се прикажуваат сите достапни записи.",
	"anyColumnOption": "Која било колона",
	"trueLabel": "Точно",
	"falseLabel": "Неточно",
	"radioTrueLabel": "Точна вредност",
	"radioFalseLabel": "Неточна вредност",
	"beginTimeRangeLabel": "Започни вредност на опсег на време",
	"endTimeRangeLabel": "Заврши вредност на опсег на време",
	"beginDateRangeLabel": "Започни вредност на опсег на датуми",
	"endDateRangeLabel": "Заврши вредност на опсег на датуми",
	"startsWithExpr": "${0}*",

//NestedSort
	singleSort: "Единично сортирање",
	nestedSort: "Вгнездено сортирање",
	ascending: "Кликнете за да се сортира по нагорен редослед",
	descending: "Кликнете за да се сортира по надолен редослед",
	sortingState: "${0} - ${1}",
	unsorted: "Не ја сортирај колоната",
	waiSingleSortLabel: "${0} - е сортирано според ${1}. Изберете да сортирате според ${2}",
	waiNestedSortLabel:"${0} - е вгнездено сортирано според ${1}. Изберете вгнездено сортирање според ${2}",

//PaginationBar
	pagerWai: 'Пејџер',

	pageIndex: '${0}',
	pageIndexTitle: 'Страница ${0}',

	firstPageTitle: 'Прва страница',
	prevPageTitle: 'Претходна страница',
	nextPageTitle: 'Следна страница',
	lastPageTitle: 'Последна страница',

	pageSize: '${0}',
	pageSizeTitle: '${0} ставки по страница',
	pageSizeAll: 'Сите',
	pageSizeAllTitle: 'Сите ставки',

	description: '${0} - ${1} од ${2} ставки.',
	descriptionEmpty: 'Решетката е празна.',

	summary: 'Вкупно: ${0}',
	summaryWithSelection: 'Вкупно: ${0} Избрани: ${1}',

	gotoBtnTitle: 'Оди на одредена страница',

	gotoDialogTitle: 'Оди на страница',
	gotoDialogMainMsg: 'Наведете го бројот на страницата:',
	gotoDialogPageCount: '(${0} страници)',
	gotoDialogOKBtn: 'Оди',
	gotoDialogCancelBtn: 'Откажи',
	// for drop down pagination bar
	pageLabel: 'Страница',
	pageSizeLabel: 'Редови',

//QuickFilter
	filterLabel: 'Филтер',
	clearButtonTitle: 'Исчисти филтер',
	buildFilterMenuLabel: 'Вгради филтер&hellip;',
	apply: 'Примени филтер',

//Sort
	helpMsg: '${0} - Кликнете за да сортира или кликнете на копчето Control за да се додаде за сортирање',
	singleHelpMsg: '${0} - Кликнете за да се сортира',
	priorityOrder: 'приоритет на сортирање${0}',

//SummaryBar
	summaryTotal: 'Вкупно: ${0}',
	summarySelected: 'Избрани: ${0}',
	summaryRange: 'Опсег: ${0}-${1}',	//need translation

//Other
	indirectSelectAll: "Притиснете ПРАЗНО за да ги означите сите.",	//need translation
	indirectDeselectAll: "Притиснете ПРАЗНО за да ги поништите сите.",	//need translation
	treeExpanded: "Копче Control + копче стрелка лево за собирање на редот.",	//need translation
	treeCollapsed: "Копче Control + копче стрелка десно за проширување на редот."	//need translation
});

